name: Update Stats

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: 0 15 * * *

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: canoypa/readme-stats-action@631b2d8be60beb5fe66abb95106ba0b71ba39586 # v0.3.1
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          template: "template.md"
      - uses: EndBug/add-and-commit@290ea2c423ad77ca9c62ae0f5b224379612c0321 # v10.0.0
        with:
          message: Update README Stats
          default_author: github_actions
