name: Update Stats

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: 0 */6 * * *

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: canoypa/readme-stats-action@v0.1.0
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
      - uses: EndBug/add-and-commit@v9
        with:
          message: Update README Stats
          default_author: github_actions
